version: '3.8'

services:
  app:
    build: .
    container_name: concrete_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/concrete_db
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=secret
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: postgres:latest
    container_name: concrete_db
    environment:
      POSTGRES_DB: concrete_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
