version: '3.8'

services:
  app:
    build: .
    container_name: concrete_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/concrete_db
      - PORT=3000
      - NODE_ENV=development
      - JWT_SECRET=secret
    depends_on:
      - db
      - migrate
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:latest
    container_name: concrete_db
    environment:
      POSTGRES_DB: concrete_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: postgres:latest
    container_name: concreteai-be-assignment-migrate
    environment:
      - PGPASSWORD=password
    command: |
      sh -c '
        until pg_isready -h db -p 5432; do
          echo "Waiting for db to be ready...";
          sleep 2;
        done;
        psql -h db -U postgres -d concrete_db -f /migrations/20240820093746_init/migration.sql
      '
    depends_on:
      - db
    volumes:
      - /home/eeq/Desktop/rengga/concreteAI-be-assignment/src/prisma/migrations:/migrations


volumes:
  postgres_data:
